const FRASES = [
  "Se eu pudesse escolher um lugar no mundo para passar todos os dias da minha vida, escolheria dentro do teu abraço.",
  "Você não precisa ser perfeita para ser o meu paraíso, basta ser você.",
  "Em cada batida do meu coração existe um nome, e esse nome é Paty.",
  "O amor que sinto por você não cabe em palavras, transborda em olhares.",
  "Paty, você é o poema mais bonito que eu jamais soube escrever.",
  "Se amar fosse um vício, você seria a minha mais linda dependência.",
  "O teu sorriso ilumina até os meus dias mais escuros.",
  "Eu não precisei do mundo inteiro, precisei de você.",
  "Cada manhã ao seu lado é o meu destino favorito.",
  "Você é a resposta para todas as perguntas que o meu coração sempre fez.",
  "O destino pode até ter criado as estrelas, mas foi o amor que criou os nossos caminhos.",
  "Sou dois, quando estou contigo: eu, e a felicidade.",
  "Se o amor é feito de sonhos, então a Paty é o meu sonho acordado.",
  "Meu lugar seguro é o teu colo, minha morada é o teu coração.",
  "Você chegou sem avisar e ficou sem querer ir, e eu não quero que vá.",
  "O universo é imenso, mas o meu mundo cabe inteiro em ti.",
  "Amo você do jeito que a brisa ama a flor: suave, constante e essencial.",
  "Paty, você é a música que embala os meus dias.",
  "Se preciso escolher entre o sol e a lua, escolho você, que é os dois.",
  "O teu nome é a oração mais bonita que eu sei dizer.",
  "Todo ouro do mundo não vale o brilho do teu olhar.",
  "Você é a calmaria depois de todas as tempestades da minha vida.",
  "Eu te amei no primeiro segundo e continuo amando a cada eternidade.",
  "Quem tem um amor assim como o nosso tem o mapa da felicidade.",
  "Se o tempo pudesse parar, eu pararia nos teus braços.",
  "Você é a minha prova de que os finais felizes existem.",
  "Amo os teus detalhes, do jeito que você respira ao teu jeito de amar.",
  "Paty, o meu coração só aprendeu a bater certo depois de você.",
  "Não é sobre ter o mundo, é sobre ter você nele.",
  "Você é a flor mais linda do jardim da minha vida.",
  "Cada saudade que tenho de você é o meu coração pedindo mais você.",
  "Se um dia eu me perder, que seja nos teus olhos.",
  "Você transformou a minha rotina em um conto de fadas.",
  "Nada é tão bonito quanto o que eu sinto por você.",
  "Paty, você é o meu ontem, o meu hoje e o meu sempre.",
  "O amor da minha vida tem nome, e esse nome é o seu.",
  "Entre mil pessoas no mundo, os meus olhos só encontram você.",
  "Você é a poesia que meu coração recita todas as noites.",
  "Se eu pudesse, escreveria o seu nome em todas as estrelas do céu.",
  "Com você, até o silêncio é música para a minha alma.",
  "Você é a certeza que eu nunca soube que precisava.",
  "O teu carinho é o único remédio que eu sempre quero tomar.",
  "Antes de você eu vivia; depois de você, eu existo por você.",
  "O teu amor é o melhor presente que a vida me deu.",
  "Paty, contigo aprendi que o paraíso não é um lugar, é um sentimento.",
  "Se as palavras pudessem voar, as minhas pousariam todas em você.",
  "Você é o sorriso que acalma a minha alma.",
  "Amar você é a minha melhor inspiração, meu melhor poema, meu melhor tudo.",
  "Eu não escolhi amar você, o meu coração escolheu.",
  "Você é a parte mais bonita de todas as minhas versões.",
  "O mundo pode mudar, mas o meu sentimento por você é eterno.",
  "Paty, você é a dona dos meus dias e da paz das minhas noites.",
  "Meu amor por você cresce a cada olhar, a cada abraço, a cada 'eu te amo'.",
  "Você é a minha doce certeza em meio a tantas dúvidas.",
  "Se amor se pesasse, o meu por você não caberia em nenhuma balança.",
  "O teu abraço é o lugar onde todas as minhas dores descansam.",
  "Você é o motivo dos meus sonhos sorrirem.",
  "A Paty é a dona do meu coração, e ele é dela sem hora para voltar.",
  "Eu te amo mais do que as palavras conseguem contar.",
  "Quando eu olho para você, vejo o meu futuro inteirinho.",
  "Você é a razão pela qual a minha vida tem sentido.",
  "O amor que sinto por você é como o mar: imenso e sem fim.",
  "Paty, você é a melhor escolha que eu já fiz na vida.",
  "Se eu pudesse renascer mil vezes, eu te amaria em todas elas.",
  "O teu riso é a banda sonora da minha felicidade.",
  "Com você, aprender a amar foi a lição mais fácil do mundo.",
  "Você é o abrigo onde o meu coração se sente em casa.",
  "O meu mundo fica mais bonito sempre que você existe nele.",
  "Paty, você me mostrou que o amor vale a pena.",
  "Se o meu coração tivesse um dono, o nome nele seria o seu.",
  "Você é a estrela que guia todas as minhas noites.",
  "A minha querida, o meu dengo, o meu amor sem medida.",
  "Você é a poesia que o meu silêncio sente.",
  "Eu olho para o futuro e só consigo enxergar você ao meu lado.",
  "O teu amor é o meu combustível para vencer todos os dias.",
  "Você é a minha sorte, o meu 'sim' eterno.",
  "Amar você não é uma escolha, é a minha única natureza.",
  "Paty, você é o vestido do meu coração: feita sob medida para mim.",
  "Se eu tivesse que escolher de novo, eu escolheria você em todas as vidas.",
  "Você é a ternura que a minha vida precisava.",
  "O teu olhar é o espelho onde o meu mundo se reflete em beleza.",
  "Eu te amo com a delicadeza de quem guarda o mais valioso tesouro.",
  "Você é o sonho que eu jamais quero acordar.",
  "Paty, você é a minha paz em forma de gente.",
  "O amor da nossa história é o meu livro favorito.",
  "Cada segundo ao seu lado vale mais que uma eternidade longe de você.",
  "Você é a primavera que floresce dentro de mim o ano inteiro.",
  "Minha razão sorri com você, minha alma dança por você.",
  "Você é mais bonita que todas as palavras que eu já aprendi.",
  "Paty, o meu coração escolheu você sem pedir licença, e é para sempre.",
  "Se existe um céu na terra, é dentro dos teus braços.",
  "Você é o meu conto favorito, a minha história que não tem fim.",
  "Eu te amo em todos os idiomas do meu coração.",
  "O teu carinho é o doce que adoça todos os meus dias.",
  "Você é a saudade boa que sempre faz tão bem.",
  "Paty, você transformou a minha vida em uma canção de amor.",
  "Se eu pudesse dar um presente ao mundo, seria o teu sorriso.",
  "Você é o 'para sempre' que eu prometi ao meu coração.",
  "O teu nome é a palavra mais bonita que eu sei dizer.",
  "Você é o meu lar, não importa onde o mundo me leve.",
  "Paty, amar você é o meu propósito de viver.",
  "Eu te amo do tamanho do céu, que aliás, sempre me lembra você.",
  "Você é a luz que faz o meu caminho brilhar.",
  "Se um dia eu perder a memória, deixa só a lembrança de te amar.",
  "O teu amor me fez acreditar em milagres.",
  "Você é o meu sim para a vida, o meu sim para a felicidade.",
  "Paty, você é a dona da minha atenção, do meu tempo e do meu coração.",
  "Se eu pudesse, guardaria cada segundo seu num pote de amor.",
  "Você é a beleza que os meus olhos se orgulham de admirar.",
  "Amar você é o verbo que conjugo em todos os tempos da minha vida.",
  "Você é a inspiração dos meus sonhos mais lindos.",
  "Paty, o meu coração floresce quando você me chama de seu.",
  "Eu te amo de um jeito que nem o infinito alcança.",
  "Você é o aconchego que a minha alma procurava.",
  "O teu sorriso é o raiar do sol em cada amanhecer meu.",
  "Você é o melhor e mais bonito dos meus planos.",
  "Paty, você é o amor que sempre escrevi entre versos.",
  "Se o mundo acabasse amanhã, o meu último pensamento seria você.",
  "Você é a minha religião, e o meu culto é te amar.",
  "O teu abraço é o remédio que cura qualquer ferida minha.",
  "Eu te amo mais hoje do que ontem, e menos do que amanhã.",
  "Você é o pedacinho de céu que caiu no meu colo.",
  "Paty, você é a sinfonia que a minha vida escolheu tocar.",
  "Se eu fosse poeta, só escreveria sobre você.",
  "Você é a beleza que dispensa qualquer outro espetáculo.",
  "O meu amor por você é a única certeza que me acompanha.",
  "Você é a maré que me leva sempre para o seu coração.",
  "Paty, contigo eu descobri que o eterno começa agora.",
  "Eu te amo de todos os jeitos: de manhã, de tarde, de noite, sempre.",
  "Você é a estrela mais bonita da minha constelação.",
  "O teu toque é a poesia que o meu corpo sente.",
  "Você é o capítulo mais feliz da minha história.",
  "Paty, a minha vida tem mais cores desde que você pinta nela.",
  "Se o amor é uma arte, você é a minha obra-prima.",
  "Você é o refrão que eu nunca me canso de ouvir.",
  "O meu lugar favorito no mundo todo é ao seu lado.",
  "Você é o doce repouso de todas as minhas noites.",
  "Paty, você é a resposta que o meu coração sempre procurou.",
  "Eu te amo com uma intensidade que o tempo não consegue vencer.",
  "Você é a força que eu busco nos meus dias difíceis.",
  "O teu olhar é o porto onde a minha alma âncora.",
  "Você é o que há de mais sagrado dentro de mim.",
  "Paty, você é a minha sorte grande em meio a tanta gente.",
  "Se eu tivesse que resumir a minha vida em uma palavra, ela seria você.",
  "Você é o vento que me faz navegar em mares de felicidade.",
  "O teu amor é a melhor coisa que eu já recebi.",
  "Você é a poesia que o meu coração recita sem cansar.",
  "Paty, você é a minha oração mais ouvida.",
  "Eu te amo do tamanho de todos os oceanos juntos.",
  "Você é o sorriso que tem cabeceira de livro, o meu predileto.",
  "O meu coração se ilumina inteiro quando você chega.",
  "Você é a calmaria que o meu mar precisa.",
  "Paty, você é o meu destino favorito em todas as viagens.",
  "Se a vida é uma trilha, você é o meu caminho mais bonito.",
  "Você é a joia mais rara do meu coração.",
  "Eu te amo de um jeito que até as estrelas têm inveja.",
  "O teu nome é o meu feitiço preferido.",
  "Você é a memória mais doce dos meus dias.",
  "Paty, você é a certeza que eu levo para o resto da minha vida.",
  "Se eu pudesse controlar o tempo, eu o gastaria todo com você.",
  "Você é o melhor da vida: simples, sincero e eterno.",
  "O teu amor me ensinou a acreditar em felizes para sempre.",
  "Você é o abraço que me faz esquecer do mundo.",
  "Paty, você é a minha compaixão, a minha ternura, o meu tudo.",
  "Eu te amo com a força das marés e a suavidade do luar.",
  "Você é a página em branco onde escrevo os meus melhores versos.",
  "O teu sorriso é o selo da minha alegria.",
  "Você é o motivo pelo qual eu acordo feliz todos os dias.",
  "Paty, o meu amor por você não tem prazo de validade.",
  "Se eu tivesse um coração de papel, o nome escrito nele seria o seu.",
  "Você é o atalho mais bonito para a felicidade.",
  "O teu amor é o meu maior tesouro nesta vida.",
  "Você é a canção que embala os meus sonhos.",
  "Paty, você é o meu olhar mais profundo e o meu sentimento mais puro.",
  "Eu te amo mais do que eu consigo imaginar em palavras.",
  "Você é a razão do meu orgulho e da minha doce loucura.",
  "O teu abraço é o meu lugar mais seguro.",
  "Você é o brilho que os meus olhos procuram em qualquer lugar.",
  "Paty, você é a minha promessa de amor para todas as estações.",
  "Se eu pudesse doar a minha eternidade, eu a daria para você.",
  "Você é o segredo mais bonito que o meu coração já guardou.",
  "O teu amor é a fonte que nunca seca dentro de mim.",
  "Você é a delicadeza que o mundo precisa.",
  "Paty, você é a minha paz em forma de gente linda.",
  "Eu te amo em todos os formatos, de todos os tamanhos, em toda a eternidade.",
  "Você é o eco do meu coração quando ele chama por amor.",
  "O teu sorriso resolve as dores que nem a medicina explica.",
  "Você é a beleza que paralisa o meu tempo.",
  "Paty, você é o meu 'eu te amo' mais sincero.",
  "Se a felicidade tivesse um rosto, seria o teu.",
  "Você é o bom dia que transforma as minhas manhãs.",
  "O teu amor é o prêmio que eu mais orgulho de ter.",
  "Você é o caminho que o meu coração escolheu para amar.",
  "Paty, você é a melodia que a minha alma toca sem parar.",
  "Eu te amo com toda a minha alma e com todos os meus dias.",
  "Você é o sonho que eu conto todas as noites antes de dormir.",
  "O teu olhar é o meu nome escrito em letras de luz.",
  "Você é o abraço onde todas as minhas certezas moram.",
  "Paty, você é a razão de todas as minhas borboletas.",
  "Se o amor fosse uma foto, a nossa seria eternizada no meu coração.",
  "Você é a fome que só o teu carinho sacia.",
  "O teu sorriso é o roteiro mais bonito da minha vida.",
  "Você é a primavera que nunca sai do meu jardim.",
  "Paty, você é a minha segunda-feira mais feliz em pleno domingo.",
  "Eu te amo do jeito mais puro que o meu coração sabe.",
  "Você é a estrela que brilha mesmo nos dias de chuva.",
  "O teu amor é o melhor capítulo da minha existência.",
  "Você é o sorriso que me faz paquerar a vida.",
  "Paty, você é a minha escolha para todas as minhas vidas.",
  "Se o tempo é um rio, você é a margem onde eu quero ficar.",
  "Você é a poesia que há em tudo o que eu vejo.",
  "O teu abraço é o aconchego que o meu coração procura.",
  "Você é o melhor presente que a vida me preparou.",
  "Paty, você é a dona dos meus sonhos e das minhas manhãs.",
  "Eu te amo de uma forma tão grande que até o infinito é pequeno.",
  "Você é a música que toca quando o meu coração te vê."
];